---
- name: Gather facts if needed
  ansible.builtin.setup:
    gather_subset:
      - os_family
  when: ansible_facts.os_family is not defined

- name: Ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts.os_family | lower == 'debian'

- name: Ensure accountsservice package is installed
  ansible.builtin.package:
    name: accountsservice
    state: present

- name: Ensure accountsservice service is enabled
  ansible.builtin.systemd:
    name: accounts-daemon
    enabled: true

- name: Include tasks
  ansible.builtin.include_tasks:
    file: users.yml
  loop: '{{ accountsservice_users }}'
  loop_control:
    loop_var: outer_item
