---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: fedora
    box: generic/fedora37
  - name: rocky
    box: generic/rocky8
  - name: debian
    box: generic/debian11
provisioner:
  name: ansible
verifier:
  name: ansible
